# Generated by Django 2.2.6 on 2019-11-23 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0002_itemcarrinho'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itemcarrinho',
            options={'ordering': ('user',)},
        ),
    ]
